import os
from patterns import PATTERNS

DEFAULT_EXCLUDES = {'.git', 'node_modules', 'venv', '.venv', '__pycache__', 'tests', 'test', '__tests__', 'spec', 'specs', 'dist', 'build', 'out', 'coverage', '.next', '.nuxt', '.idea', '.vscode', 'vendor', 'tmp', 'temp', 'logs'}

def is_binary_file(filepath):
    """
    A simple heuristic to detect binary files by checking for null bytes in the first chunk.
    """
    try:
        with open(filepath, 'rb') as f:
            chunk = f.read(1024)
            if b'\0' in chunk:
                return True
    except Exception:
        pass # If we can't read it, we'll likely fail later anyway, but let's assume not binary for now
    return False

def scan_file_lines(filepath, content_generator):
    """
    Scans lines generated by content_generator and yields findings.
    """
    findings = []
    for line_num, line in enumerate(content_generator, 1):
        if len(line) > 1000:
            continue
        for name, (pattern, severity) in PATTERNS.items():
            for match in pattern.finditer(line):
                # The secret is either group 1 (if defined) or the full match
                if match.lastindex:
                    secret = match.group(1)
                else:
                    secret = match.group(0)
                
                findings.append({
                    "file": filepath,
                    "line": line_num,
                    "type": name,
                    "secret": secret,
                    "severity": severity
                })
    return findings

def scan_local_path(target_path, excludes=None, full_scan=False):
    """
    Walks the target path locally and scans files.
    """
    if excludes is None:
        excludes = []
    
    exclude_dirs = DEFAULT_EXCLUDES.union(set(excludes))
    all_findings = []
    files_scanned = 0

    if os.path.isfile(target_path):
        if not is_binary_file(target_path):
            files_scanned += 1
            with open(target_path, 'r', encoding='utf-8', errors='ignore') as f:
                all_findings.extend(scan_file_lines(target_path, f))
        return all_findings, files_scanned

    for root, dirs, files in os.walk(target_path):
        # Modify dirs in-place to skip excluded directories and test directories
        new_dirs = []
        for d in dirs:
            if d in exclude_dirs:
                continue
            if not full_scan:
                d_lower = d.lower()
                if d_lower in {'test', 'tests', '__tests__', 'spec', 'specs', 'e2e', 'cypress', 'load_tests'}:
                    continue
                if d_lower.endswith('_tests') or d_lower.endswith('_test') or d_lower.startswith('test_'):
                    continue
            new_dirs.append(d)
        dirs[:] = new_dirs

        for file in files:
            # Skip some common binary extensions just in case
            if file.endswith(('.exe', '.dll', '.so', '.dylib', '.png', '.jpg', '.jpeg', '.gif', '.pdf', '.svg', '.ico', '.mp4', '.mp3', '.wav', '.zip', '.tar', '.gz', '.lock', '.sum')):
                continue

            filepath = os.path.join(root, file)
            
            # Skip explicitly excluded files
            if file in excludes:
                continue
                
            # Skip test files broadly if not full_scan
            if not full_scan:
                f_lower = file.lower()
                if f_lower.startswith('test_') or f_lower.endswith(('_test.py', '_test.go', '_test.rb', '.test.js', '.test.jsx', '.test.ts', '.test.tsx', '.spec.js', '.spec.jsx', '.spec.ts', '.spec.tsx')):
                    continue

            if is_binary_file(filepath):
                continue
            
            files_scanned += 1
            try:
                with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                    all_findings.extend(scan_file_lines(filepath, f))
            except Exception:
                pass # Ignore unreadable files

    return all_findings, files_scanned
